# Generated by Django 4.0.5 on 2022-06-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_ingredient_recipeingredients_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
