# Generated by Django 4.0.5 on 2022-06-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_rename_ingredient_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food/', verbose_name='Картинка'),
        ),
    ]
