# Generated by Django 4.0.5 on 2022-06-19 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_id_alter_follow_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribe',
            field=models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Подписка'),
        ),
    ]
