# Generated by Django 4.0.5 on 2022-06-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='subscribe',
            new_name='is_subscribed',
        ),
    ]
